def build(bld):

    comp_prefix = bld.get_name_prefix(
        toolchain = bld.toolchain,
        platform  = bld.platform)
# Component cifXApplicationDemoEthernetIFDefinitions ----------------------------------------------
    
    bld.sdkcomponent(
        name            = "EthernetIFDefinitions_sdk",
        export_includes = "Includes/EthernetIF_API",
        )


# Component cifXApplicationDemoGenericAPDefinitions ----------------------------------------------
    
    bld.sdkcomponent(
        name            = "GenericAPDefinitions_sdk",
        export_includes = "Includes\GenericAP_API",
        )


# Component cifXApplicationDemoHilscherDefinitions ----------------------------------------------
    
    bld.sdkcomponent(
        name            = "Hil_Definition_netXFirmware_sdk",
        export_includes = "Includes/HilscherDefinitions",
        )
    

# Component cifXApplicationDemoECSDefinitions ----------------------------------------------
    
    bld.sdkcomponent(
        name            = "ECSDefinitions_sdk",
        export_includes = "Includes/ECS_API",
        )

# Component cifXApplicationDemoSocketDefinitions ----------------------------------------------
    
    bld.sdkcomponent(
        name            = "SocketDefinitions_sdk",
        export_includes = "Includes/Socket_API",
        )

# Component cifXApplicationDemoWebIFDefinitions ----------------------------------------------
    
    bld.sdkcomponent(
        name            = "WebIFDefinitions_sdk",
        export_includes = "Includes/WebIF_API",
        )
