/**************************************************************************************
 Copyright (c) Hilscher Gesellschaft fuer Systemautomation mbH. All Rights Reserved.
***************************************************************************************
$Id: Ecs_ErrorCodes.h 90745 2020-03-06 09:46:42Z Sven $:


Changes:
 Date          Description
 -----------------------------------------------------------------------------------
 yyyy-mm-dd    created
**************************************************************************************/

#ifndef _ECS_ERRORCODES_H
#define _ECS_ERRORCODES_H

#ifndef ECS_ERROR_TABLE_BEGIN
#define ECS_ERROR_TABLE_BEGIN typedef enum ECS_ERROR_CODE_Etag {
#endif

#ifndef ECS_ERROR_RESULT
#define ECS_ERROR_RESULT(x, v) x = v,
#endif

#ifndef ECS_ERROR_TABLE_END
#define ECS_ERROR_TABLE_END   ECS_ERROR_CODE_VALUE_RANGE = 0xFFFFFFFF } ECS_ERROR_CODE_E;
#endif

ECS_ERROR_TABLE_BEGIN
#ifndef ECS_ERROR_TABLE_EXCLUDE_COMMON_ERRORS
ECS_ERROR_RESULT(ECS_SUCCESS, 0)

ECS_ERROR_RESULT(ECS_ERROR_FAIL, 0xC0000001)
ECS_ERROR_RESULT(ECS_ERROR_UNEXPECTED, 0xC0000002)
ECS_ERROR_RESULT(ECS_ERROR_OUT_OF_MEMORY, 0xC0000003)
ECS_ERROR_RESULT(ECS_ERROR_UNKNOWN_COMMAND, 0xC0000004)
ECS_ERROR_RESULT(ECS_ERROR_INVALID_PARAMETER, 0xC0000009)
ECS_ERROR_RESULT(ECS_ERROR_WATCHDOG_TIMEOUT, 0xC000000C)
ECS_ERROR_RESULT(ECS_ERROR_INVALID_SEQUENCE, 0xC000000F)
ECS_ERROR_RESULT(ECS_ERROR_REQUEST_RUNNING, 0xC000001A)
ECS_ERROR_RESULT(ECS_ERROR_NOT_CONFIGURED, 0xC0000119)
ECS_ERROR_RESULT(ECS_ERROR_CONFIGURATION_FAULT, 0xC0000120)
ECS_ERROR_RESULT(ECS_ERROR_INSUFFICIENT_LICENSE, 0xC0000123)
ECS_ERROR_RESULT(ECS_ERROR_PARAMETER_ERROR, 0xC0000124)
ECS_ERROR_RESULT(ECS_ERROR_REMANENT_DATA_MISSING, 0xC000012E)
ECS_ERROR_RESULT(ECS_ERROR_NETWORK_FAULT, 0xC0000140)
ECS_ERROR_RESULT(ECS_ERROR_CONNECTION_TIMEOUT, 0xC0000142)
ECS_ERROR_RESULT(ECS_ERROR_CABLE_DISCONNECT, 0xC0000145)
ECS_ERROR_RESULT(ECS_ERROR_BUS_OFF, 0xC0000180)
ECS_ERROR_RESULT(ECS_ERROR_CONFIG_IS_LOCKED, 0xC0000181)
ECS_ERROR_RESULT(ECS_ERROR_APPLICATION_ALREADY_REGISTERED, 0xC0000201)
ECS_ERROR_RESULT(ECS_ERROR_NO_APPLICATION_REGISTERED, 0xC0000202)
#endif

ECS_ERROR_RESULT(ECS_ERROR_COE_EMERG_MSG_NOT_SENT, 0xC0B1001C)
ECS_ERROR_RESULT(ECS_ERROR_COE_EMERG_MSG_INVALID_PRIORITY, 0xC0B1001D)

ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_STRUCTURE, 0xC0AE0006)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_ECS_CONFIG, 0xC0AE0008)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM_CONFIG, 0xC0AE0009)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM0_CONFIG, 0xC0AE000A)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM1_CONFIG, 0xC0AE000B)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM2_CONFIG, 0xC0AE000C)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM3_CONFIG, 0xC0AE000D)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM4_CONFIG, 0xC0AE000E)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM5_CONFIG, 0xC0AE000F)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM6_CONFIG, 0xC0AE0010)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_SM7_CONFIG, 0xC0AE0011)
ECS_ERROR_RESULT(ECS_ERROR_NXD_INVALID_HSK_CONFIG, 0xC0AE0013)

ECS_ERROR_RESULT(ECS_ERROR_ESM_RX_SIZE_EXCEEDS_MAX, 0xC0AF000C)
ECS_ERROR_RESULT(ECS_ERROR_ESM_TX_SIZE_EXCEEDS_MAX, 0xC0AF000D)
ECS_ERROR_RESULT(ECS_ERROR_ESM_SUM_OF_TX_AND_RX_EXCEEDS_MAX, 0xC0AF000E)
ECS_ERROR_RESULT(ECS_ERROR_ESM_SM_LENGTH_NOT_ALLOWED, 0xC0AF0011)
ECS_ERROR_RESULT(ECS_ERROR_ESM_SUM_OF_SM_LENGTH_EXCEEDS_MAX_SIZE, 0xC0AF0012)
ECS_ERROR_RESULT(ECS_ERROR_ESM_INVALID_SM_STARTADDRESS, 0xC0AF0013)
ECS_ERROR_RESULT(ECS_ERROR_ESM_SM2_STARTADDR_OVERLAP_SM3_STARTADDR, 0xC0AF0014)
ECS_ERROR_RESULT(ECS_ERROR_ESM_SM_STARTADDR_EXCEED_DATA_AREA, 0xC0AF0015)
ECS_ERROR_RESULT(ECS_ERROR_ESM_MBX_AREA_AND_SM_STARTADDR_OVERLAP, 0xC0AF0016)

ECS_ERROR_RESULT(ECS_ERROR_ESM_INVALID_SII_BYTE_SIZE, 0xC0AF0070)
ECS_ERROR_RESULT(ECS_ERROR_ESM_STDMBX_MAX_SIZE_TOO_LARGE, 0xC0AF0080)
ECS_ERROR_RESULT(ECS_ERROR_ESM_STDMBX_MIN_SIZE_TOO_SMALL, 0xC0AF0081)
ECS_ERROR_RESULT(ECS_ERROR_ESM_STDMBX_DEF_SIZE_TOO_SMALL, 0xC0AF0082)
ECS_ERROR_RESULT(ECS_ERROR_ESM_STDMBX_DEF_SIZE_TOO_LARGE, 0xC0AF0083)
ECS_ERROR_RESULT(ECS_ERROR_ESM_BOOTMBX_SIZE_TOO_LARGE, 0xC0AF0090)
ECS_ERROR_RESULT(ECS_ERROR_ESM_BOOTMBX_SIZE_TOO_SMALL, 0xC0AF0091)

ECS_ERROR_RESULT(ECS_ERROR_ESM_FOE_TIMEOUT_TOO_SMALL, 0xC0AF00A0)
ECS_ERROR_RESULT(ECS_ERROR_ESM_COE_TIMEOUT_TOO_SMALL, 0xC0AF00B0)
ECS_ERROR_RESULT(ECS_ERROR_ESM_COE_INVALID_DETAILS, 0xC0AF00B1)
ECS_ERROR_RESULT(ECS_ERROR_ESM_COE_INVALID_FLAGS, 0xC0AF00B2)
ECS_ERROR_RESULT(ECS_ERROR_ESM_COE_SUPPORT_NOT_AVAIL, 0xC0AF00C0)
ECS_ERROR_RESULT(ECS_ERROR_ESM_SOE_SUPPORT_NOT_AVAIL, 0xC0AF00C1)
ECS_ERROR_RESULT(ECS_ERROR_ESM_COE_SDOINFO_NOT_AVAIL, 0xC0AF00C2)
ECS_ERROR_RESULT(ECS_ERROR_ESM_EOE_SUPPORT_NOT_AVAIL, 0xC0AF00C3)
ECS_ERROR_RESULT(ECS_ERROR_ESM_FOE_SUPPORT_NOT_AVAIL, 0xC0AF00C4)
ECS_ERROR_RESULT(ECS_ERROR_ESM_AOE_SUPPORT_NOT_AVAIL, 0xC0AF00C5)

ECS_ERROR_RESULT(ECS_ERROR_ESM_REQUEST_DESTINATION_PROBLEM, 0xC0AFF000)

ECS_ERROR_RESULT(ECS_ERROR_EOE_PARAM_NO_IP_SUPPORT, 0xC0B20003)
ECS_ERROR_RESULT(ECS_ERROR_EOE_PARAM_NO_DHCP_SUPPORT, 0xC0B20007)

ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_MDP_MAPPED_RANGE_START, 0xC0F00000)
/* all codes map to high word = low error code word, low word = 0x700 */
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_MDP_MAPPED_RANGE_END, 0xC0F0FFFF)

ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_MAPPED_RANGE_START, 0xC1140000)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INVALID_GROUP, 0xC1140702)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INVALID_OFFSET, 0xC1140703)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INVALID_ACCESS, 0xC1140704)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INVALID_SIZE, 0xC1140705)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INVALID_DATA, 0xC1140706)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_NOT_READY, 0xC1140707)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_BUSY, 0xC1140708)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_NO_MEMORY, 0xC114070A)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INVALID_PARM, 0xC114070B)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_NOT_FOUND, 0xC114070C)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_INCOMPATIBLE, 0xC114070E)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_NOT_INIT, 0xC1140718)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_TIMEOUT, 0xC1140719)
ECS_ERROR_RESULT(ECS_ERROR_AOE_RESULT_MAPPED_RANGE_END, 0xC114FFFF)

ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_NOT_DEFINED, 0xC0B38000)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_NOT_FOUND, 0xC0B38001)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_ACCESS_DENIED, 0xC0B38002)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_DISK_FULL, 0xC0B38003)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_ILLEGAL, 0xC0B38004)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_ALREADY_EXISTS, 0xC0B38006)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_NO_USER, 0xC0B38007)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_BOOTSTRAP_ONLY, 0xC0B38008)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_NOT_IN_BOOTSTRAP, 0xC0B38009)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_NO_RIGHTS, 0xC0B3800A)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_PROGRAM_ERROR, 0xC0B3800B)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_CHECKSUM_WRONG, 0xC0B3800C)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_FIRMWARE_DOES_NOT_FIT, 0xC0B3800D)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_FILE_HEADER_DOES_NOT_EXIST, 0xC0B38010)
ECS_ERROR_RESULT(ECS_ERROR_FOE_RESULT_FLASH_PROBLEM, 0xC0B38011)

ECS_ERROR_TABLE_END

#endif
