def build(bld):
    
    toolchain   = "gccarmemb"
    bld.toolchain   = toolchain
    bld.platform  = "netx90"
    comp_prefix = bld.get_name_prefix(
        toolchain = bld.toolchain,
        platform  = bld.platform)
        
# Component netx_HostAbstractionLayer -------------------------------------------------------------
    netx_studio_sources = [
        "Sources/netX_hostAbstractionLayer.c", 
        ]
    
    includes = [
        "Includes",
        ]
       
    bld.stlib(
        target          = "netx90_HostAbstractionLayer",
        name            = comp_prefix + "netx90_HostAbstractionLayer",
        description     = "Host abstraction layer for nxhx90-jtag application",
        displaygroup    = "Libraries",
platform        = "netx90",
        toolchain       = toolchain,
        use             = [
                           "hostabstractionlayer_sdk",
                           "cifXToolkit_sdk",
                           "netx_drv_sdk",
                          ],
        source          = netx_studio_sources,
        includes        = includes,
        export_includes = includes,
    )
    
    bld.sdkcomponent(
        name            = "netx90_HostAbstractionLayer_sdk",
        export_includes = includes,
    )
